ready project
MambaJDev/java-filmorate pull request #23
Opened 2024-05-12 19:32 UTC by MambaJDev

2024-05-12 21:53 UTC, SashaTyutyaev approved these changes

2024-05-15 01:54 UTC, afomkina requested changes
Всем привет! Очень сильно извиняюсь за такую огромную задержку, у меня был шторм и достаточно долго не могли восстановить электричество и связь. Надеюсь, что такого больше не повториться 🙏

Вы проделали большую работу! У вас получился хороший проект и появились навыки работы в команде. Осталось поправить некоторые моменты, чтобы сделать код лаконичнее.

Сейчас не хватает описания всех фичей в описании пулл реквеста или в файле README. Нужно обязательно добавить

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +@Data
Зачем здесь `Data`? Если только для того, чтобы заинжектить `DirectorService`, то нужно использовать [@RequiredArgsConstrutor](https://www.baeldung.com/java-lombok-constructor-annotation)

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                       @RequestParam(required = false) String by) {
Лучше переименовать, так как не очень понятно, что такое by

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!(sortBy.equals("year") || sortBy.equals("likes"))) {
Данную проверку нужно перенести в сервис, так как это часть бизнес-логики программы

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewsController.java
> +    ReviewsService reviewsService;
Не хватает модификатора доступа

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewsController.java
> +@Slf4j
Логирование в данном контроллере не используется, аннотация лишняя

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/director/DirectorDaoImpl.java
> +@Data
Зачем тут Data?

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDaoImpl.java
> +import java.util.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/ru/using-wildcard-imports-in-java/#:~:text=%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D0%BE%D0%B4%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BE%D1%87%D0%BD%D1%8B%D1%85%20%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D0%BE%D0%B2%20%D0%BD%D0%B8%D0%BA%D0%B0%D0%BA%20%D0%BD%D0%B5,%D1%81%D1%82%D0%BE%D0%BB%D0%BA%D0%BD%D1%83%D1%82%D1%8C%D1%81%D1%8F%20%D1%81%20%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%BE%D0%B9%20%D0%BA%D0%BE%D0%BD%D1%84%D0%BB%D0%B8%D0%BA%D1%82%D0%B0%20%D0%B8%D0%BC%D0%B5%D0%BD.) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDaoImpl.java
> +            String sql2 = "delete from films_genres";
Лучше переименовать названия переменных. Важно давать осмысленные названия, чтобы код было проще читать и поддерживать

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDaoImpl.java
> +            String sql4 = "delete from films_users where film_id = ?";
Лучше не использовать цифры/числа в названиях переменных

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDaoImpl.java
> +        String sqlAllUsersIdWhoLikedSameFilms = "select distinct user_id from films_users where film_id in " +
Нужно использоваться join, вместо множественных селектов

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDaoImpl.java
> +        for (Long userId : usersId) {
Циклы нужно заменить на [stream api](https://www.baeldung.com/java-8-streams)

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDaoImpl.java
> +        return data.stream().collect(Collectors.toList());
Лучше использовать конструктор
```suggestion
        return new ArrayList<>(data);
```

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDaoImpl.java
> +        String sqlQueryByDirector = "select * from films where id in (select film_id from film_director where director_id in " +
Все множественные селекты нужно переписать с помощью join

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/film/FilmDaoImpl.java
> +            return unionSet.stream().collect(Collectors.toList());
Лучше использовать конструктор вместо стрима

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/user/UserDaoImpl.java
> +            String sql3 = "delete from friends where user_id = ?";
Лучше переименовать переменные более осмысленно, чтобы код было проще читать и поддерживать

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +@Data
Я предпочитаю использовать только нужные аннотации, вместо сборной Data, так как она приводит к ряду неочевидных проблем, с которыми мы столкнемся в следующих спринтах.
 Оставлю интересную статью [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5) для саморазвития. 
**Исправлять  ничего в рамках данного комментария не нужно**

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/director/DirectorDBService.java
> +@Data
Зачем тут `@Data`?

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/film/InMemoryFilmService.java
>  public class InMemoryFilmService implements FilmService {
InMemory реализации больше не используются, их лучше удалить

2024-05-15 01:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/user/InMemoryUserService.java
Больше не используется, лучше удалить

2024-05-15 01:54 UTC, afomkina commented on src/test/java/ru/yandex/practicum/filmorate/dao/reviews/ReviewsDaoImplTest.java
> +        Review review1 = new Review(1, "Плохой фильм", false, 0, 1, 1);
Одинаковые объекты в тестах лучше создавать в `@BeforeEach` или с помощью отдельных методов, чтобы избежать множественных дублирований кода

2024-05-15 19:34 UTC, MambaJDev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                                       @RequestParam(required = false) String by) {
В postman тестах by поэтому оставили by

2024-05-17 00:15 UTC, afomkina approved these changes
Молодцы, что выбрали усложнённую версию и добавили режиссера в поиск.
 
Работа выглядит отлично! Вы хорошо разобрались во взаимодействие между слоями сервис-контроллер-репозиторий и у вас получились отличные запросы к таблицам.  Так держать 💪

2024-05-17 00:15 UTC, afomkina commented on README.md
🔥

2024-12-09 23:42 UTC, closed without merging