refactor: final project 10 added friends likes
MambaJDev/java-filmorate pull request #6
Opened 2024-04-02 13:36 UTC by MambaJDev

2024-04-02 13:40 UTC, MambaJDev commented
Привет! В общем пытался исправить - добавить тесты - в итоге удалил репозиторий)  Пришлось все заново восстанавливать. Не суди строго) Получил колоссальный опыт ))

2024-04-03 16:34 UTC, afomkina requested changes

2024-04-03 16:34 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    private String getStacktrace(Exception exception) {
Лучше не выводить стектрейс, так как чаще всего он огромный и столько информации пользователю не нужно. Предлагаю его удалить и оставить только `message`

2024-04-03 16:34 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    private static class ErrorResponse {
Нужно вынести в отдельный файл и сделать класс публичным, при этом убрав `static`

2024-04-03 16:34 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getPopularFilms(@RequestParam(defaultValue = "10") Integer count) {
Лучше сделать дефолтное значение константой

2024-04-03 16:34 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Set<Long> usersIdWhoLike = new HashSet<>();
Отличный выбор коллекции!

2024-04-03 16:34 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private final Map<Long, Film> films;
Нужно инициализировать значением при объявлении

2024-04-03 16:34 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    private final Map<Long, User> users;
Нужно инициализировать значением при объявлении

2024-04-03 16:34 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/user/InMemoryUserService.java
> +        for (Long firstId : userFriends) {
Нужно переписать с помощью `stream api`

2024-04-04 13:54 UTC, afomkina approved these changes

2024-04-04 13:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final String defaultCount = "10";
Константы в java принято именовать в `SNAKE_CASE`

2024-04-04 13:54 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/user/InMemoryUserService.java
> +        return userStorage.getUserById(userId).getFriends().stream()
🔥

2024-04-04 14:06 UTC, MambaJDev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final String defaultCount = "10";
Точно) совсем вылетело ) исправлю

2024-04-04 14:13 UTC, merged